version: '3.5'
services:
  inzfs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    ports:
      - "80:443"
  webapplication-tests:
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results.trx
      - --results-directory /out/testresults
      - targetdir:/out/testresults/coverage/reports
      - reporttypes:HTMLInline;HTMLChart"
      - /p:CollectCoverage=true
      - /p:CoverletOutputFormat=cobertura 
      - /p:CoverletOutput=/out/testresults/coverage/
      - /p:Exclude="[xunit.*]*%2c[StackExchange.*]*
      
    volumes: 
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests/}:/tests
