version: '3.4'

services:
  inzfs:
    image: ${DOCKER_REGISTRY-}inzfs
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    build:
      context: ./
      dockerfile: ./INZFS/Dockerfile