version: '3.5'
services:
  inzfs:
    image: ${DOCKER_REGISTRY-}inzfs
    build:
      context: ./
      dockerfile: ./INZFS/Dockerfile
  webapplication-tests:
    image: ${DOCKER_REGISTRY-}webapplication-tests
    build:
      context: ./
      dockerfile: ./INZFS/Dockerfile   
      target: test
