version: '3.5'
services:
  inzfs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    ports:
      - "80:443"
  webapplication-tests:
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results.trx
      - --logger 
      -  xunit;LogFileName=/tests/coverage.cobertura.xml
      - --results-directory 
      - /tests/testresults/coverage/reports 
      - /p:CollectCoverage=true
      - /p:CoverletOutputFormat=cobertura 
      - /p:CoverletOutput=/tests/testresults/coverage/
      - /p:Exclude="[xunit.*]*%2c[StackExchange.*]*
    volumes: 
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests/}:/tests
