version: '3.7'

services:

  fortio:
    image: fortio/fortio:1.17.0
    command: load -c 32 -qps 25 -t 60s https://inzfs-uat.london.cloudapps.digital/
    
  fortio2:
    image: fortio/fortio:1.17.0
    command: load -c 32 -qps 25 -t 60s https://inzfs-staging.london.cloudapps.digital/

  fortio3:
    image: fortio/fortio:1.17.0
    command: load -c 32 -qps 25 -t 60s https://inzfs-sandbox.london.cloudapps.digital/