version: '3.4'

services:
  seq:
    image: ${DOCKER_REGISTRY-}seq
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: seq
    ports:
      - 80:80
      - 5341:5341
    environment:
      ACCEPT_EULA: Y