version: '3.7'

# volumes:
#     prometheus_data: {}

services:
  prometheus:
    image: ${DOCKER_REGISTRY-}prom-blackbox
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile1
    ports:
      - 9115:9115
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    restart: always
    volumes:
      - ./config.yml:/etc/blackbox_exporter/config.yml:ro
      # - prometheus_data:/prometheus