version: '3.7'

# volumes:
#     prometheus_data: {}

services:
  prometheus:
    image: ${DOCKER_REGISTRY-}prom1
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile3
    container_name: prom1
    ports:
      - 9090:9090
    restart: always
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - prometheus_data:/prometheus