version: '3.4'
services:
  prometheus:
    image: ${DOCKER_REGISTRY-}prom
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --web.enable-lifecycle
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafanacontainer:
    image: "grafana/grafana"
    ports:
     - "3000:3000"