version: '3.7'

volumes:
     blackbox_data: {}

services:
  prometheus:
    image: ${DOCKER_REGISTRY-}prom-blackbox
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile1
    ports:
      - 9115:9115
    command:
      - '--config.file=/etc/blackbox/config.yml'
    restart: always
    volumes:
      - ./config.yml:/etc/blackbox/config.yml
      - blackbox_data:/blackbox/
