{
 "title": "EEF-DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "memory_utilization ALL Nodes",
   "type": "piechart",
   "description": "Memory utilisation in percent (0-100)",
   "gridPos": { "h": 23, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_utilization" }
   ]
  },
  {
   "title": "cpu ALL_Nodes",
   "type": "piechart",
   "description": "CPU utilisation in percent (0-100)",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "disk_utilization All_Nodes",
   "type": "timeseries",
   "description": "Disk utilisation in percent (0-100",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 14 },
   "targets": [
    { "expr": "disk_utilization" }
   ]
  },
  {
   "title": "response_time_count 2xx All_Nodes",
   "type": "timeseries",
   "description": "Timing of processed requests broken down by status_range label",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum without(instance, job, guid, organisation) (rate(response_time_count{status_range=\"2xx\"}[15m]))"
    }
   ]
  },
  {
   "title": "requests 2xx All_Nodes",
   "type": "graph",
   "description": "Number of requests processed broken down by status_range label",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, guid, organisation) (rate(requests{status_range=\"2xx\"}[15m]))"
    }
   ]
  },
  {
   "title": "memory_utilization",
   "type": "gauge",
   "description": "Memory utilisation in percent (0-100)",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memory_utilization{app=\"inzfs-lab\"}[1h]))"
    }
   ]
  },
  {
   "title": "disk_utilization inzfs-prom",
   "type": "gauge",
   "description": "Disk utilisation in percent (0-100",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(disk_utilization{app=\"inzfs-prom\"}[1h]))"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "gauge",
   "description": "CPU utilisation in percent (0-100)",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-lab\"}[1h]))"
    }
   ]
  },
  {
   "title": "disk_utilization",
   "type": "gauge",
   "description": "Disk utilisation in percent (0-100",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(disk_utilization{app=\"inzfs-lab\"}[1h]))"
    }
   ]
  },
  {
   "title": "requests 2xx",
   "type": "graph",
   "description": "Number of requests processed broken down by status_range label",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, guid, organisation) (rate(requests{app=\"inzfs-lab\" ,status_range=\"2xx\"}[15m]))"
    }
   ]
  },
  {
   "title": "response_time_count 2xx",
   "type": "graph",
   "description": "Timing of processed requests broken down by status_range label",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, guid, organisation) (rate(response_time_count{app=\"inzfs-lab\" ,status_range=\"2xx\"}[15m]))"
    }
   ]
  }
 ]
}