version: '3.4'

volumes:
  grafana_data: {}

services:
  grafana:
    image: ${DOCKER_REGISTRY-}prom-grafana
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${grafana_admin}
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_password}
      - GF_USERS_ALLOW_SIGN_UP=false
