global:
  resolve_timeout: 1m

route:
  # group_by: ['app']
  receiver: 'zulip-notifications'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'zulip-notifications'
  webhook_configs:
  - url: 'https://inzfs.zulipchat.com/api/v1/external/alertmanager?api_key=kyE0xjHUv8tMoT0VABpSvzdMhpbGtn0w=stream%20name&name=host&desc=AlertManager'
    send_resolved: true