version: '3.4'

volumes:
  alertmanager_data: {}

services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager
    ports:
      - 9093:443
    restart: always
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    - ./alertmanager_data:/alertmanager
    - ./templates:/etc/alertmanager/templates
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    - '--storage.tsdb.path=/alertmanager'
    - '--web.external-url=https://inzfs-prom-alertmanager.london.cloudapps.digital'
    - '--web.listen-address=0.0.0.0:9093'
    - '--cluster.listen-address=0.0.0.0:9094'
    - '--cluster.advertise-address=0.0.0.0:9094'
    - '--cluster.settle-timeout=60s'