version: '3.4'
services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager
    ports:
    - 9093:9093
    restart: always
    privileged: true
    volumes:
    - ./alertmanager/:/etc/alertmanager/
    - alertmanager_data:/alertmanager
    - ./config.yml:/etc/alertmanager/config.yml:ro
    - ./alertmanager/config.yml:/config.yml
    - ./alertmanager/config.yml:/etc/config.yml
    command:
    - '--config.file=/etc/config.yml'
    - '--storage.path=/alertmanager'
volumes:
  alertmanager_data: