version: '3.4'
services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager
    ports:
    - 9093:9093
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.tsdb.path=/alertmanager'
    volumes:
    - ./config/config.yml:/etc/alertmanager/config.yml
    - alertmanager_data:/alertmanager
volumes:
  alertmanager_data: