version: '3.4'
services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager
    ports:
    - 9093:9093
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
    - ./alertmanager/:/etc/alertmanager/
    - alertmanager_data:/alertmanager
volumes:
  alertmanager_data: