version: '3.4'
services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager
    ports:
    - 9093:9093
    restart: always
    privileged: true
    volumes:
    - ./config.yml:/etc/alertmanager/config.yml:ro
    command:
    - '--config.file=/etc/alertmanager/config.yml'
    - '--storage.tsdb.path=/alertmanager'