version: '3.4'
services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager
    ports:
      - 9093:9093
    restart: always
    privileged: true
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    - ./alertmanager:/alertmanager
    - ./templates:/etc/alertmanager/templates
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    - '--storage.tsdb.path=/alertmanager'
    - '--web.external-url=http://inzfs-prom-alertmanager.london.cloudapps.digital:9093'