version: '3.4'

volumes:
  alertmanager_data: {}

services:
  alertmanager:
    image: ${DOCKER_REGISTRY-}prom-alertmanager1
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: prom-alertmanager1
    ports:
      - 9093:9093
      - 9094:9094
    restart: always
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    - ./alertmanager_data:/alertmanager
    - ./templates:/etc/alertmanager/templates
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    - '--storage.tsdb.path=/alertmanager'
    - '--web.external-url=http://inzfs-prom-alertmanager1.london.cloudapps.digital/api/v2/alerts'
    - '--web.listen-address=10.255.151.228:9093'
    #- '--cluster.advertise-address=0.0.0.0:9094'
    - '--cluster.listen-address=0.0.0.0:9094'
    - '--cluster.settle-timeout=2m'
    - '--cluster.peer=10.255.244.192:9094'
    - '--cluster.advertise-address=10.255.151.228:9094'