{
 "title": "LAB2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "process_cpu_seconds_total{ instance=\"inzfs-lab2.london.cloudapps.digital:443\"}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{ instance=\"inzfs-lab2.london.cloudapps.digital:443\"}"
    }
   ]
  },
  {
   "title": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{instance=\"inzfs-lab2.london.cloudapps.digital:443\",code=\"200\"}[15m]))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{instance=\"inzfs-lab2.london.cloudapps.digital:443\",code=\"200\"}[15m]))"
    }
   ]
  },
  {
   "title": "dotnet_total_memory_bytes{instance=\"inzfs-lab2.london.cloudapps.digital:443\"}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{instance=\"inzfs-lab2.london.cloudapps.digital:443\"}"
    }
   ]
  },
  {
   "title": "http_requests_received_total{instance=\"inzfs-sandbox.london.cloudapps.digital:443\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_requests_received_total{instance=\"inzfs-sandbox.london.cloudapps.digital:443\"}"
    }
   ]
  }
 ]
}