{
 "title": "eef-webapp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (response_time_count{app=\"inzfs-prod\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Time / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space, le) (rate(response_time_bucket{app=\"inzfs-prod\"}[15m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "graph",
   "description": "The response time value for a transaction below which 95% of the response times lie",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.95, sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (rate(response_time_bucket{app=\"inzfs-prod\", status_range=\"2xx\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "cpu_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-prod\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "memory_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(memory_utilization{app=\"inzfs-prod\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "Staging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (response_time_count{app=\"inzfs-staging\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Time / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space, le) (rate(response_time_bucket{app=\"inzfs-staging\"}[15m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "graph",
   "description": "The response time value for a transaction below which 90% of the response times lie",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.95, sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (rate(response_time_bucket{app=\"inzfs-staging\", status_range=\"2xx\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "cpu_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-staging\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "memory_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(memory_utilization{app=\"inzfs-staging\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "UAT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (response_time_count{app=\"inzfs-uat\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Time / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space, le) (rate(response_time_bucket{app=\"inzfs-uat\"}[15m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "graph",
   "description": "The response time value for a transaction below which 90% of the response times lie",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (rate(response_time_bucket{app=\"inzfs-uat\", status_range=\"2xx\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "cpu_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-uat\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "memory_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(memory_utilization{app=\"inzfs-staging\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "Sandbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (response_time_count{app=\"inzfs-sandbox\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Time / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space, le) (rate(response_time_bucket{app=\"inzfs-sandbox\"}[15m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "graph",
   "description": "The response time value for a transaction below which 90% of the response times lie",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (rate(response_time_bucket{app=\"inzfs-sandbox\", status_range=\"2xx\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "cpu_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-sandbox\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "memory_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(memory_utilization{app=\"inzfs-sandbox\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "LAB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (response_time_count{app=\"inzfs-lab\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Time / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space, le) (rate(response_time_bucket{app=\"inzfs-lab\"}[15m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "graph",
   "description": "The response time value for a transaction below which 90% of the response times lie",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 37 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (rate(response_time_bucket{app=\"inzfs-lab\", status_range=\"2xx\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "cpu_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-lab\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "memory_utilization Memory currently in use in percent (0-100)",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(memory_utilization{app=\"inzfs-lab\"})",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}