groups:
  - name: Alerts
    rules:
      - alert: InstanceDown Critical!!
        expr: up{env!="lab2"} == 0
        for: 1m
        labels:
          severity: critical
          env: test
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."


      - alert: LAB2 InstanceDown Critical!!
        expr: up{env="lab2"} == 0
        for: 1m
        labels:
          severity: critical
          env: prod
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."


