global:
  resolve_timeout: 1m

route:
  # group_by: ['app']
  receiver: 'zulip-notifications'

receivers:
- name: 'zulip-notifications'
  webhook_configs:
  - url: 'https://inzfs.zulipchat.com/api/v1/external/alertmanager?api_key=kyE0xjHUv8tMoT0VABpSvzdMhpbGtn0w=stream%20name&name=host&desc=alertmanager'
    send_resolved: true