groups:
  - name: Alerts
    rules:
      - alert: InstanceDown Critical!!
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: InstanceCrashed Critical!!
        expr: crash>0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has crashed."

      # - alert: PrometheusJobMissing
      #   expr: absent(up{job="prometheus"})
      #   for: 0m
      #   labels:
      #     severity: warning
      #   annotations:
      #     summary: Prometheus job missing (instance {{ $labels.instance }})
      #     description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: PrometheusAllTargetsMissing
        expr: count by (job) (up) == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Prometheus all targets missing (instance {{ $labels.instance }})
          description: "A Prometheus job does not have living target anymore.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualNetworkThroughputIn All Nodes
        expr: (rate(http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",le="1.024"}[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host unusual network throughput in (instance {{ $labels.instance }})
          description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostLowDiskSpace All Nodes
        expr: disk_utilization{organisation="beis-netzero"} > 60
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out low disk space (instance {{ $labels.instance }})
          description: "Disk is 60%  full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostHighCpuLoad + 75% All Nodes
        expr: cpu{organisation="beis-netzero"} > 75
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 75%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: MemoryUsage + 75% All Nodes
        expr: sum(rate(memory_utilization{organisation="beis-netzero"}[5m])) > 75
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Server memory Usage (instance {{ $labels.instance }})
          description: "Memory usage is more than 75%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: http response time slow 2xx All Nodes
        expr: (rate(response_time_bucket{le="0.5",status_range="2xx"}[5m])) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary:  probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Response Time Slow 2xx All Nodes
        expr: histogram_quantile(0.95, (rate(response_time_bucket{status_range="2xx"}[5m]))) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: Response Time Slow All Requests All Nodes
        expr: (rate(response_time_bucket{organisation="beis-netzero"}[5m])) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"