groups:
  - name: Alerts
    rules:
      - alert: InstanceDown Critical!!
        expr: up{env!="prod"} == 0
        for: 1m
        labels:
          severity: critical
          env: test
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: InstanceDown Critical - prod
        expr: up{env="prod"} == 0
        for: 1m
        labels:
          severity: critical
          env: prod
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: High average CPU usage
        expr: cpu{app!="inzfs-prod"} > 200
        for: 1m
        labels:
          severity: warning
          env: test
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 95%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: High average CPU usage - prod
        expr: avg(cpu{app="inzfs-prod"}) > 200
        for: 1m
        labels:
          severity: warning
          env: prod
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 95%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: High usage of Disk Space
        expr: disk_utilization{app!="inzfs-prod"} > 70
        for: 1m
        labels:
          severity: critical
          env: test
        annotations:
          summary: Host out low disk space (instance {{ $labels.instance }})
          description: "Disk is 60%  full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: High usage of Disk Space - prod
        expr: avg_over_time(disk_utilization{app = "inzfs-prod"}[15m]) > 70
        for: 1m
        labels:
          severity: critical
          env: prod
        annotations:
          summary: Host out low disk space (instance {{ $labels.instance }})
          description: "Disk is 70%  full (< 20% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: High usage of Memory
        expr: avg_over_time(memory_utilization{app!="inzfs-lab2"}[5m]) > 75
        for: 1m
        labels:
          severity: warning
          env: test
        annotations:
          summary: Server memory Usage (instance {{ $labels.instance }})
          description: "Memory usage is more than 75%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: High usage of Memory - prod
        expr: avg_over_time(memory_utilization{app="inzfs-lab2"}[5m]) > 75
        for: 1m
        labels:
          severity: warning
          env: prod
        annotations:
          summary: Server memory Usage (instance {{ $labels.instance }})
          description: "Memory usage is more than 75%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


