version: '3.7'

# volumes:
#     prometheus_data: {}

services:
  prometheus:
    image: ${DOCKER_REGISTRY-}prom
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile
    container_name: prom
    ports:
      - 9090:9090
    restart: always
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - prometheus_data:/prometheus

  blackbox_exporter:
    build:
      context: ./
      dockerfile: ./prometheus/Dockerfile1
    ports:
      - 9115:9115
    command:
      - '--config.file=/etc/blackboxexporter/config.yml'
    restart: always