global:
  scrape_interval: 30s
  scrape_timeout: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - https://inzfs-prom-alertmanager.london.cloudapps.digital

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.yml'
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-prom.london.cloudapps.digital']

  - job_name: 'exporter'
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['prometheus-exporter-beis-netzero.london.cloudapps.digital']
        labels:
          env: develop