global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - 'alert.yml'
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-prom.london.cloudapps.digital']

  - job_name: prometheus_exporter
    scrape_interval: 1s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['prometheus-exporter-beis-netzero.london.cloudapps.digital']