global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - 'alert.yml'
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'

  - job_name: prometheus_exporter
    scrape_interval: 1s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['prometheus-exporter-beis-netzero.london.cloudapps.digital']