global:
  scrape_interval: 60s
  scrape_timeout: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - scheme: https
      static_configs:
      - targets:
        - inzfs-prom-alertmanager.london.cloudapps.digital

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.yml'
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'exporter'
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['prometheus-exporter-beis-netzero.london.cloudapps.digital']
        labels:
          env: develop

  - job_name: 'lab-exporter'
    scrape_interval: 5m
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-lab.london.cloudapps.digital']
        labels:
          env: lab
    
  - job_name: 'lab3-health'
    scrape_interval: 5m
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-lab3.london.cloudapps.digital']
        labels:
          env: lab3

  - job_name: 'sandbox-exporter'
    scrape_interval: 2m
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-sandbox.london.cloudapps.digital']
        labels:
          env: sandbox

  - job_name: 'uat-exporter'
    scrape_interval: 2m
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-uat.london.cloudapps.digital']
        labels:
          env: uat

  - job_name: 'staging-exporter'
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-staging.london.cloudapps.digital']
        labels:
          env: staging

  - job_name: 'prod-exporter'
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['inzfs-prod.london.cloudapps.digital']
        labels:
          env: prod