{
 "title": "eef-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "http response time over 24hr Period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space, le) (rate(response_time_bucket{app=\"inzfs-staging\"}[24h]))"
    }
   ]
  },
  {
   "title": "CPU response time over 24h Period",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(cpu{app=\"inzfs-staging\"}[24h]))"
    }
   ]
  },
  {
   "title": "95% Quantile response Time over 24h period.",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum without(instance, exported_instance, alertstate, endpoint, job, organisation, guid, status_range, space) (rate(response_time_bucket{app=\"inzfs-staging\", status_range=\"2xx\"}[24h])))"
    }
   ]
  }
 ]
}