# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: https://inzfs-prom.london.cloudapps.digital
  editable: true                        # whether it should be editable
  is_default: true                      # whether this should be the default DS

- name: InfluxDB
  type: influxdb
  access: proxy
  database: defaultdb
  user: $(influxdbuser)
  password: $(influxdbpass)
  url: https://prod-lon-4602c7bc-01c1-4043-9230-966b9e11014b-paas-cf-prod.aivencloud.com:19676