name: "dotnetbuild"

on: 
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --framework 5.0.x --configuration Release --no-restore
