global:
  resolve_timeout: 1m
#  pagerduty_url: https://events.eu.pagerduty.com/generic/2010-04-15/create_event.json

  # Sendgrid SMTP properties.
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'inzfs.prod-alerts@beis.gov.uk'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '$(SMTP_APIKEY)'

receivers:
# - name: 'zulip-notifications'
#   webhook_configs:
#   - url: 'https://inzfs.zulipchat.com/api/v1/external/alertmanager?api_key=$(zulip_api_key)'
#     send_resolved: true

#- name: 'pagerduty-notifications'
#  pagerduty_configs:
#  - service_key: $(PAGER_DUTY_SERVICEKEY)
#    send_resolved: true
    
- name: mail-dev
  email_configs:
  - to: "inzfs.alerts@beis.gov.uk"
    from: "inzfs.alerts@beis.gov.uk"
    headers:
      Subject: "[TEST Alert]: {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }}) - ({{ .Status }})"
    html: |
      Greetings,
      <p>
      You have the following firing {{ .CommonLabels.severity }} alerts:
      <ul>
      {{ range .Alerts }}
      <li>{{.Labels.alertname}} on {{.Labels.instance}}</li>
      <li>Labels:</li>
      <li>{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
      <li>{{ end }}Annotations:</li>
      <li>{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
      <li>{{ end }}---</li>
      {{ end }}
      </ul>
      </p>

- name: mail-prod
  email_configs:
  - to: "inzfs.prod-alerts@beis.gov.uk"
    headers:
      Subject: "[PROD Alert]: {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }}) - ({{ .Status }})"
    html: |
      Greetings,
      <p>
      You have the following firing {{ .CommonLabels.severity }} alerts:
      <ul>
      {{ range .Alerts }}
      <li>{{.Labels.alertname}} on {{.Labels.instance}}</li>
      <li>Labels:</li>
      <li>{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
      <li>{{ end }}Annotations:</li>
      <li>{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
      <li>{{ end }}---</li>
      {{ end }}
      </ul>
      </p>
      
route:
  receiver: mail-dev
  group_by: [alertname, env]
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1m
  routes:
  - receiver: mail-prod
    repeat_interval: 1m
    matchers: 
     - env="prod"
  - receiver: mail-dev
    repeat_interval: 1m
    matchers: 
     - env="test"
