global:
  resolve_timeout: 1m

route:
  # group_by: ['app']
  receiver: 'zulip-notifications'

receivers:
- name: 'zulip-notifications'
  webhook_configs:
  - url: 'https://eef.zulipchat.com/api/v1/external/alertmanager?api_key=yrHqcJEK0Pabi2zWPvf2uCzjSVx8RBOm&stream=Prometheus'
    send_resolved: true