global:
  resolve_timeout: 1m

route:
  # group_by: ['app']
  receiver: 'my-gmail'

receivers:
- name: my-gmail
  email_configs:
  - to: davidmarkgardiner@gmail.com
    send_resolved: true
    from: davidmarkgardiner@gmail.com+alertmanager@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: davidmarkgardiner@gmail.com@gmail.com
    auth_identity: davidmarkgardiner@gmail.com@gmail.com
    auth_password: uxhmngyjolnlxqtv